server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oadzo5byw0ygrKlv0h7
            client-secret: -u0wNNMVV5maG0Z-woWIG-4Z4U-jix1DDb3xBsRw
        provider:
          okta:
            authorization-uri: https://dev-158606.oktapreview.com/oauth2/v1/authorize
            token-uri: https://dev-158606.oktapreview.com/oauth2/v1/token
            user-info-uri: https://dev-158606.oktapreview.com/oauth2/v1/userinfo
            jwk-set-uri: https://dev-158606.oktapreview.com/oauth2/v1/keys
